"""create_tables

Revision ID: 42efcbfd9f9e
Revises: 
Create Date: 2025-06-05 20:23:05.903257

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv('FLASK_ENV')
SCHEMA = os.getenv('SCHEMA')

# revision identifiers, used by Alembic.
revision = '42efcbfd9f9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('farm', sa.String(length=50), nullable=True),
    sa.Column('varietal', sa.String(length=50), nullable=True),
    sa.Column('process', sa.String(length=50), nullable=False),
    sa.Column('roaster', sa.String(length=50), nullable=False),
    sa.Column('roast_profile', sa.String(length=25), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flavor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.Column('grinder', sa.String(length=50), nullable=True),
    sa.Column('grind_size', sa.Numeric(scale=2), nullable=True),
    sa.Column('brewer', sa.String(length=50), nullable=True),
    sa.Column('ratio', sa.Numeric(scale=4), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffees_flavor_notes',
    sa.Column('coffee_id', sa.Integer(), nullable=False),
    sa.Column('flavor_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['flavor_note_id'], ['flavor_notes.id'], ),
    sa.PrimaryKeyConstraint('coffee_id', 'flavor_note_id')
    )

    if environment is "production":
        op.execute(f"ALTER TABLE coffees SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE flavor_notes SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE brews SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE coffees_flavor_notes SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffees_flavor_notes')
    op.drop_table('brews')
    op.drop_table('flavor_notes')
    op.drop_table('coffees')
    # ### end Alembic commands ###
