"""empty message

Revision ID: 8afeb1689ad3
Revises: 30e05a46cf1a
Create Date: 2025-06-05 15:07:30.453495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afeb1689ad3'
down_revision = '30e05a46cf1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=7), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffees', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
