"""Add Users table

Revision ID: 9bf25cde141b
Revises: c1de788c63dc
Create Date: 2025-11-15 14:58:03.924160

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv('FLASK_ENV')
SCHEMA = os.getenv('SCHEMA')

# revision identifiers, used by Alembic.
revision = '9bf25cde141b'
down_revision = 'c1de788c63dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    if environment is "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
