"""add user_id fk on brews and coffees

Revision ID: b939bd2a5001
Revises: 9bf25cde141b
Create Date: 2025-12-13 15:40:35.240320

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv('FLASK_ENV')
SCHEMA = os.getenv('SCHEMA')

# revision identifiers, used by Alembic.
revision = 'b939bd2a5001'
down_revision = '9bf25cde141b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('users_brews_fk', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('coffees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('users_coffees_fk', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coffees', schema=None) as batch_op:
        batch_op.drop_constraint('users_coffees_fk', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.drop_constraint('users_brews_fk', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
