"""empty message

Revision ID: 044961f0a1b4
Revises: c9aefb6eb616
Create Date: 2025-06-14 07:28:27.401390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044961f0a1b4'
down_revision = 'c9aefb6eb616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Numeric(scale=1), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), server_default=sa.text('(CURRENT_DATE)'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.drop_column('date')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
