"""empty message

Revision ID: 81b7119e2f7b
Revises: 79dedbd94c7c
Create Date: 2025-06-24 12:10:48.989380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column, select


# revision identifiers, used by Alembic.
revision = '81b7119e2f7b'
down_revision = '79dedbd94c7c'
branch_labels = None
depends_on = None


def upgrade():
    brews_table = table('brews',
        column('grinder', sa.String),
        column('grind_size', sa.Numeric),
        column('dose', sa.Numeric),
        column('brewer', sa.String),
        column('water_amt', sa.Numeric),
        column('water_temp', sa.Numeric),
        column('celsius', sa.Boolean),
        column('ratio', sa.Numeric),
        column('recipe', sa.String))
        
    recipes_table = table('recipes',
        column('grinder', sa.String),
        column('grind_size', sa.Numeric),
        column('dose', sa.Numeric),
        column('brewer', sa.String),
        column('water_amt', sa.Numeric),
        column('water_temp', sa.Numeric),
        column('celsius', sa.Boolean),
        column('ratio', sa.Numeric),
        column('details', sa.String))
    
    insert_stmt = (
        recipes_table.insert().from_select(
            ['grinder', 'grind_size', 'dose', 'brewer', 'water_amt', 'water_temp', 'celsius', 'ratio', 'details'],
            select(
                brews_table.c.grinder,
                brews_table.c.grind_size,
                brews_table.c.dose,
                brews_table.c.brewer,
                brews_table.c.water_amt,
                brews_table.c.water_temp,
                brews_table.c.celsius,
                brews_table.c.ratio,
                brews_table.c.recipe
            )
        )
    )

    op.execute(insert_stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_brews_recipe_id_recipes', 'recipes', ['recipe_id'], ['id'])
        batch_op.drop_column('recipe')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_brews_recipe_id_recipes', type_='foreignkey')
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
