"""empty message

Revision ID: c9aefb6eb616
Revises: 42efcbfd9f9e
Create Date: 2025-06-13 15:29:21.974935

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv('FLASK_ENV')
SCHEMA = os.getenv('SCHEMA')

# revision identifiers, used by Alembic.
revision = 'c9aefb6eb616'
down_revision = '42efcbfd9f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dose', sa.Numeric(scale=2), nullable=True))
        batch_op.add_column(sa.Column('water_amt', sa.Numeric(scale=2), nullable=True))
        batch_op.add_column(sa.Column('recipe', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brews', schema=None) as batch_op:
        batch_op.drop_column('recipe')
        batch_op.drop_column('water_amt')
        batch_op.drop_column('dose')

    # ### end Alembic commands ###
