"""add_recipes_name_col

Revision ID: c1de788c63dc
Revises: 79dedbd94c7c
Create Date: 2025-06-24 13:26:35.532753

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv('FLASK_ENV')
SCHEMA = os.getenv('SCHEMA')

# revision identifiers, used by Alembic.
revision = 'c1de788c63dc'
down_revision = '79dedbd94c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=(None if environment == "development" else SCHEMA)) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=(None if environment == "development" else SCHEMA)) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
