"""empty message

Revision ID: 79dedbd94c7c
Revises: ab0334f13f57
Create Date: 2025-06-24 12:01:26.363089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dedbd94c7c'
down_revision = 'ab0334f13f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grinder', sa.String(length=50), nullable=True),
    sa.Column('grind_size', sa.Numeric(scale=2), nullable=True),
    sa.Column('dose', sa.Numeric(scale=2), nullable=True),
    sa.Column('brewer', sa.String(length=50), nullable=True),
    sa.Column('water_amt', sa.Numeric(scale=2), nullable=True),
    sa.Column('water_temp', sa.Numeric(scale=0), nullable=True),
    sa.Column('celsius', sa.Boolean(), nullable=True),
    sa.Column('ratio', sa.Numeric(scale=4), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    # ### end Alembic commands ###
