"""add user_id fk to recipes

Revision ID: 627bf66abefa
Revises: b939bd2a5001
Create Date: 2026-01-03 16:53:19.307034

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv('FLASK_ENV')
SCHEMA = os.getenv('SCHEMA')

# revision identifiers, used by Alembic.
revision = '627bf66abefa'
down_revision = 'b939bd2a5001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('users_recipes_fk', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('users_recipes_fk', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
