"""create tables coffees, brews, flavor_notes

Revision ID: 30e05a46cf1a
Revises: 
Create Date: 2024-04-05 19:32:11.881433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e05a46cf1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('farm', sa.String(length=50), nullable=True),
    sa.Column('varietal', sa.String(length=50), nullable=True),
    sa.Column('process', sa.String(length=50), nullable=False),
    sa.Column('roaster', sa.String(length=50), nullable=False),
    sa.Column('roast_profile', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flavor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('brews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffee_id', sa.Integer(), nullable=True),
    sa.Column('grinder', sa.String(length=50), nullable=True),
    sa.Column('grind_size', sa.Numeric(scale=2), nullable=True),
    sa.Column('brewer', sa.String(length=50), nullable=True),
    sa.Column('ratio', sa.Numeric(scale=4), nullable=True),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('coffees_flavor_notes',
    sa.Column('coffee_id', sa.Integer(), nullable=False),
    sa.Column('flavor_note_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coffee_id'], ['coffees.id'], ),
    sa.ForeignKeyConstraint(['flavor_note_id'], ['flavor_notes.id'], ),
    sa.PrimaryKeyConstraint('coffee_id', 'flavor_note_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffees_flavor_notes')
    op.drop_table('brews')
    op.drop_table('flavor_notes')
    op.drop_table('coffees')
    # ### end Alembic commands ###
